version: '3'

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 24454:24454/udp
      - 25565:25565/tcp
      - 25565:25565/udp
    environment:
      EULA: 'TRUE'
      TYPE: 'FABRIC'
      MEMORY: '2G'
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./data:/data
